### ISSUE TITLE
Coupon code and Alma payment

### ISSUE THREAD

**Issue by hharvel** [alma/alma-monthlypayments-magento2#10]
Hello.

When choose first to make a payment with Alma, the order is created and set to "Pending payment" status. So if you used a single-use coupon code for this payment, you can't draw back and change your payment method.

**To Reproduce**
1. Create a new Cart Price Rules with a coupon in Magento Back Office
2. Make an order that use the rule
3. Go to checkout an choose Alma payment
4. See the order created and in "Pending payment" status in the Back Office
5. Check in database the `times_used` at 1 for the coupon in `salesrule_coupon` table

**Expected behavior**
Have a way to go back to the payment method selection, so the customer can pay another way with his coupon.

**Magento version**
2.3.6-p1

**Plugin version**
6.5.0

**Comment by Francois-Gomis** [comment]
Hi,
in the new version 2.8.0 you have the possibility to cancel pending orders at payment expiration ( you can configure payment expiration time ).
You need to contact your sale or support to activate "expiration notification"  for magento.
Thanks.
