### ISSUE TITLE
Error getOrderShippingMethodName() method payment not possible 3.4.0

### ISSUE THREAD

**Issue by jules-ndp** [alma/alma-monthlypayments-magento2#100]
Hello,

when I make a payment in 3.4.0, I get this error :

`TypeError(code: 0): Alma\\MonthlyPayments\\Helpers\\OrderHelper::getOrderShippingMethodName(): Return value must be of type string, null returned at vendor/almapay/alma-monthlypayments-magento2/Helpers/OrderHelper.php:164)`

**Comment by fronke** [comment]
me too :cry:
