### ISSUE TITLE
Code generation failed with php 7.3 and v4.1.0

### ISSUE THREAD

**Issue by lapriqua** [alma/alma-monthlypayments-magento2#114]
Hi,

Seems the class \Alma\MonthlyPayments\Controller\Payment\Eligibility is not compatible with php version previous 7.4. The fact that the $logger property is typed break this compatibility.

**Comment by KevinOxwork** [comment]
Hi, 
Do you think that if we do this, it will work ?

![image](https://github.com/alma/alma-monthlypayments-magento2/assets/29751888/2e4ce5c5-07e9-4ded-b4de-ca0d53566420)

**Comment by lapriqua** [comment]
Hi,

Yes, it should work. That's the only thing that break the compatibility with php 7.3
