### ISSUE TITLE
Error on CSP whitelist declaration

### ISSUE THREAD

**Issue by hmadi-expertime** [alma/alma-monthlypayments-magento2#116]
Hi, I'm encountering an error on my website (developer mode) because there is an error on the csp_whitelist.xml file because you have a duplicate id on the values.

Error : 
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): More than one node matching the query: /csp_whitelist/policies/policy[@id='font-src']/values/value[@id='fonts_gstatic'], Xml is: <?xml version="1.0" encoding="UTF-8"?>...`

![image](https://github.com/alma/alma-monthlypayments-magento2/assets/113514080/5d460d4e-4862-4f0c-8d17-d54d09ae80d6)

Thanks.

**Comment by Francois-Gomis** [comment]
Hello, this issue has been fixed in the new version of the module. Thank you for your feedback.
