### ISSUE TITLE
Enable Alma payment is not active for Iphone ios

### ISSUE THREAD

**Issue by gabi77** [alma/alma-monthlypayments-magento2#123]
The alma module is not activated on the user's first visit on iPhone IOS.

What I'm talking about in the first journey is the user who arrives then logs in, chooses their delivery method and arrives on the payment solutions page. Alma does not activate.

But if we return to the basket and redo all the steps, the Alma payment solution is displayed.

Magento version 2.4.6-p3

**Comment by fplantinet** [comment]
It's not just iPhone IOS, but all browsers.

**Comment by ChristopheFerreboeuf** [comment]
This bug appears even after last update.

It is really disturbing and users get bad experience. Additionally, it is like Alma method is not provided when we advertise it.
