### ISSUE TITLE
Pending Orders for Unpaid

### ISSUE THREAD

**Issue by WebHostingAce** [alma/alma-monthlypayments-magento2#21]
This extension creates "Pending Orders" for the unpaid orders. Currently looking for a fix or workaround. 
As these "Pending Orders" reserve the stock we are facing an issue.

**Comment by Francois-Gomis** [comment]
Hi,
in the new version 2.8.0 you have the possibility to cancel pending orders at payment expiration ( you can configure payment expiration time ).
You need to contact your sale or support to activate "expiration notification"  for magento.
Thanks.
