### ISSUE TITLE
Issue with payment 3 month and badge.js

### ISSUE THREAD

**Issue by Minirock** [alma/alma-monthlypayments-magento2#39]
Hi there,

I would like to report a couple issues that i'm currently facing : 

- The first one is coming from the badge.js

```
var qtyNode = document.getElementById('qty');
qtyNode.addEventListener("input",function(){updateWidget()});
```

In some cases it looks like it is triggering a js error when the script loads before the dom

![image](https://user-images.githubusercontent.com/16558403/170662270-7a9200a9-de70-4723-b252-cc45bfc73a99.png)

As a fix attempt, I would suggest to add `domReady!` for this js file ? 

=========================================================================

- The second issue i'm facing is about the configuration of my 3x payment in product page.

As you can see, two times works fine

![image](https://user-images.githubusercontent.com/16558403/170662579-08f42916-8aca-4d15-b272-e8e4df6f1d18.png)

But not the 3 times

![image](https://user-images.githubusercontent.com/16558403/170662678-95909c40-55d9-435a-95e6-44170d856b31.png)

I've been trying to dig by myself but I can't find where this values are generated; so I don't really know what is happening.

=========================================================================

- The third one is when you go on the modal payment detail ; it looks like the html isn't properly interprated. But there again I can't find anywhere in the code where this might comes from.

![image](https://user-images.githubusercontent.com/16558403/170663143-88a205d3-f3e3-4a4d-85c6-a30d894ab987.png)

Did I missed something in the database ?  Thanks for attention

**Comment by Minirock** [comment]
Hi @Francois-Gomis 

Thanks for your update.
Looking at my magento libs, looks like our prototype.js is version 1.7

And jquery version is : jQuery JavaScript Library v1.12.4

So I think we are not falling into the use case you just specified.

**Comment by Francois-Gomis** [comment]
Hi,
Do you have un URL with an active Alma Badge ? 
Thanks

**Comment by Minirock** [comment]
No sorry only a restricted sandbox right now.  Running on a magento 2.2.6 instance.

**Comment by Francois-Gomis** [comment]
Hi Minirock,

we have identified the library  : 
it's "legacy-build.min.js"

**Comment by Minirock** [comment]
@Francois-Gomis For the update, what was causing us the issue was a third party js call is one of our custom code.

From ``app/design/frontend/Website/default/Makarovsoft_Callback/templates/form.phtml``

```
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'prototype'
            'Magento_Ui/js/modal/modal'
        ],
        function(
            jQuery,
            modal,
            prototype
            modal
        ) {
```

Removing the call to prototype fixed it. So strongly related to what you were saying about the prototype library. In our case the prototype object wasn't even used so we just had to remove it to make it work.

**Comment by Francois-Gomis** [comment]
@Minirock Thanks for the update !
