### ISSUE TITLE
Call to a member function getId() on null in vendor/alma/alma-monthlypayments-magento2/Block/Catalog/Product/View.php:110

### ISSUE THREAD

**Issue by webpar** [alma/alma-monthlypayments-magento2#56]
Hi,

I am facing the following isuse when using Magento 2.4.4, and when selecting payment "alma" on checkout page :  main.CRITICAL: Error: Call to a member function getId() on null in vendor/alma/alma-monthlypayments-magento2/Block/Catalog/Product/View.php:110

Do you know how to fix this ?

Regards

**Comment by webpar** [comment]
Hi,

Could we use the following fix :
if (!is_object($item)) {
    return false;
}

Regards

**Comment by Francois-Gomis** [comment]
HI,
do you have an other plugin on checkout ? 
By default, product view is not call on checkout page.

**Comment by Francois-Gomis** [comment]
Hi Webpar, we have changed View.php in the newt version.
Next version is in submission process and will arrive soon
