### ISSUE TITLE
Param typing too restrictive > PaymentPlansHelper::formatFeePlanConfigForSave()

### ISSUE THREAD

**Issue by thacac** [alma/alma-monthlypayments-magento2#68]
When trying to disable the payment method from BO
If $configInput is null > lead to BO getting KO with log
`main.CRITICAL: TypeError: Argument 2 passed to Alma\MonthlyPayments\Helpers\PaymentPlansHelper::formatFeePlanConfigForSave() must be of the type array, null given,`
(Mgento 2.4..2 / php 74)

**Comment by Francois-Gomis** [comment]
Thanks for this PR.
