### ISSUE TITLE
OrderStatus event if payment fails

### ISSUE THREAD

**Issue by thacac** [alma/alma-monthlypayments-magento2#70]
Orders are created with new status even if payment is KO
That led to non paid orders to my customer who uses this status to trig his ERP actions

Please propose a setting to choose order status after payment, on failure, etc. as this is done on the finetecture module for example to fit all tiers configs capabilities

**Comment by Francois-Gomis** [comment]
Hi,
we have a feature which automatically cancel pending orders.
Please contact support@getalma.eu
