### ISSUE TITLE
Checkout : SQL Error if one product of cart has no category IDs

### ISSUE THREAD

**Issue by vncnt-mb** [alma/alma-monthlypayments-magento2#77]
Hello,

When we place an order for an item (Simple product without category, or a configurable product with a child product without an assigned category), the form refuses to go to the Alma platform and displays an SQL error in customer view (even by disabling debug mode).

<img width="798" alt="Capture d’écran 2022-12-08 à 12 42 19" src="https://user-images.githubusercontent.com/48125944/206439249-c99fcd6c-adf1-42bd-b49f-88cdd0d1106b.png">

-----

I found a simple workaround, just check if the product has categories before starting the search via the repository:

https://github.com/alma/alma-monthlypayments-magento2/blob/638fda1b69512d478dacba25d1d53f4cb4f40f24/Model/Data/Quote.php#L158

```
private function getProductCategories(Product $product): array
{
  $categoryIds = $product->getCategoryIds();

  if(empty($categoryIds)) return []; # add this

  try {
    $categoryCollection = $this->getCategoryCollection($categoryIds);
  } catch (LocalizedException $e) {
    $this->logger->info(
        'Impossible to create category collection for product',
        [
            'product ID '=> $product->getId(),
            'Exception Message' => $e->getMessage()
        ]
    );
    return [];
  }
...
```

If you find anything better than my light workaround, go for it. And, if you have more questions, don't hesitate to reply me :)

Have a nice day !

**Comment by Francois-Gomis** [comment]
Hi,
thanks for your report.
I fixed this issue in the next version.
I am waiting for review.
Thanks
