### ISSUE TITLE
Magento 2.4.2 : Block issue in the back office 

### ISSUE THREAD

**Issue by hharvel** [alma/alma-monthlypayments-magento2#8]
**Magento Version :** 2.4.2
**Module Version :** 1.2.0

Hello,

I tried to update the module from 1.1.2 to 1.2.0 during a Magento migration from 2.3.5 to 2.4.2. But when I enable the module in the back office, it make the page unavailable with the following error : 

```
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: '/var/www/html/vendor/composer/../alma/alma-monthlypayments-magento2/view/adminhtml/templates/form/field/plans.phtml' in module: 'Alma_MonthlyPayments' block's name: 'adminhtml\form\field\plans_0'
```
Can you check that, please ?

**Comment by fronke** [comment]
Hi,
I have the same problem with 2.4.3.
Regards

**Comment by fronke** [comment]
@hharvel Ok I solved the problem by clearing my Alma configuration (DELETE FROM core_config_data WHERE path LIKE '%alma%')
